### ISSUE TITLE
Tarea trabajo en equipo matemáticas conversiones. Uriel, Edwin, y Araceli

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/ejercicios-equipo-de-uriel-edwin-araceli-1as#3]
[TRABAJO DE EQUIPO DE MATEMATICAS DISCRETAS.docx](https://github.com/SistemasTecTlaxiaco/ejercicios-equipo-de-uriel-edwin-araceli-1as/files/7151011/TRABAJO.DE.EQUIPO.DE.MATEMATICAS.DISCRETAS.docx)

**Comment by josealfredo79** [comment]
Falta la calificación de acuerdo a rúbrica

**Comment by yanet02** [comment]
Tu trabajo no contiene objetivos, introducción, Resultados, tampoco conclusión pero agregaste ejercicios, por lo tanto te doy el 15%

**Comment by josealfredo79** [comment]
Bueno hay que mejorar mucho el trabajo.
